- name : taskvars
  hosts: local
  connection: local
  vars:
   Course: "Devops with AWS"
   Goal: "You will get a job immediately after the course"

  tasks:
  - name: print the variables
    vars: # Task level variables 
     Course: "Scrum Master"
     Goal: "You will pass the certification,get the job"
    ansible.builtin.debug:
      msg: "It is {{ Course }},{{ Goal }}"

  - name: print the variables 1
    ansible.builtin.debug:
    msg: "It is {{ Course }},{{ Goal }}"
