- name : Variables from files
  hosts: local
  connection: local
  vars_files:
  - varsfilereferring.yaml
  tasks:
  - name: print your future
    ansible.builtin.debug:
       msg: "It is {{ Course }},{{ Goal }}"